name: Export Repository Structure

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  export-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate repository structure
        run: |
          git ls-tree -r --name-only HEAD > repo-structure.txt  

      - name: Upload repository structure as artifact
        uses: actions/upload-artifact@v3
        with:
          name: repository-structure
          path: repo-structure.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Move repository structure on archive folder to S3 if exists
        run: |
          aws s3 ls s3://${{ vars.BUCKET_NAME }}/repositoryStructure/repo-structure.txt
          if [ $? -eq 0 ]; then
            aws s3 mv s3://${{ vars.BUCKET_NAME }}/repositoryStructure/repo-structure.txt s3://${{ vars.BUCKET_NAME }}/repositoryStructure/archive/repo-structure.txt
          fi

      - name: Upload file to S3
        run: |
          aws s3 cp repo-structure.txt s3://${{ vars.BUCKET_NAME }}/repositoryStructure/