name: Export Repository Structure

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  export-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate repository structure
        run: |
          git ls-tree -r --name-only HEAD > repo-structure.txt  

      - name: Upload repository structure as artifact
        uses: actions/upload-artifact@v4
        with:
          name: repository-structure
          path: repo-structure.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Move repository structure on archive folder to S3
        run: |
          for file in $(aws s3 ls s3://${{ vars.BUCKET_NAME }}/repositoryStructure/ --recursive | awk '{print $4}'); do
            if [[ ! "$file" =~ /$ ]]; then  # Excludes folders
              aws s3 mv s3://${{ vars.BUCKET_NAME }}/repositoryStructure/$file s3://${{ vars.BUCKET_NAME }}/repositoryStructure/archive/$file
            fi
          done

      - name: Upload file to S3
        run: |
          TIMEZONE=${{ vars.TIMEZONE }} 
          if [ -z "$TIMEZONE" ]; then
            echo "TIMEZONE is not set in GitHub Variables. Defaulting to UTC."
            TIMEZONE="UTC"
          fi
          TIMESTAMP=$(TZ="${{ env.TIMEZONE }}" date +%Y%m%d%H%M%S)
          mv repo-structure.txt repo-structure-${TIMESTAMP}.txt
          aws s3 cp repo-structure-${TIMESTAMP}.txt s3://${{ vars.BUCKET_NAME }}/repositoryStructure/
