name: Test Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  test-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create a test file
        run: echo "Hello World" > test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test.txt
